### ISSUE TITLE
Get rid of the dependency on Google Translate

### ISSUE THREAD

**Issue by PureTryOut** [OpenVoiceOS/zzz-old-ovos-utils#2]
Currently this uses googletrans, which makes use of Google Translate in the background. This is a proprietary service and, well... ran by Google, which isn't known for it's good privacy.

It would be good to get rid of this dependency in the future in favor of something more privacy friendly, preferable even possible to be self-hosted and FOSS.

**Comment by JarbasAl** [comment]
happy to provide alternatives

for detection there are a few things that can be used - https://github.com/OpenVoiceOS/ovos_utils/blob/dev/ovos_utils/lang/detect.py

but for translation not really, i'm happy to make the import optional/lazy loaded and fail gracefully if missing. or even replace it with a http request

for context see the chat where this issue was raised https://chat.mycroft.ai/community/pl/95o5bcfrqbyh3rnwjwg38z6frh

**Comment by PureTryOut** [comment]
I know about [Apertium](https://www.apertium.org/) which is FOSS translating software and service. I don't know if they have an API to use but it could be useful. Source available [here](https://github.com/apertium/apertium).
