### ISSUE TITLE
phoneme_guesser missing?

### ISSUE THREAD

**Issue by forslund** [OpenVoiceOS/zzz-old-ovos-utils#75]
Installed the ovos-vlc-plugin for testing the holmesV patch fixing plugin loading in the audio service, I got import errors saying that it can't find `phoneme_guesser`. should it be moved from `install_extras` to `install_requires`?

Or should phoneme_guesser be a requirement for the vlc-plugin?

**Comment by JarbasAl** [comment]
i was avoiding adding it to requirements.txt because it bundles some data files and is some 15MB, i intend to refactor that package to download lang data on demand making it much smaller, at that point it can be added to regular requirements

the main usage is for TTS plugins (only mimic generates visimes for mk1 faceplate, phoneme_guesser is used so every engine has a mouth, even if badly timed) which were moved to `opm` so maybe it should only be used there and removed from this package? 

this would mean deprecating this https://github.com/OpenVoiceOS/ovos_utils/blob/dev/ovos_utils/lang/phonemes.py which is essentially a wrapper
